package main

import (
	"crypto/sha256"
	"encoding/hex"
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestParseOptions(t *testing.T) {
	opts, err := parseOptions([]string{"--repository", "OWNER/sbx-connect", "--tag", "v1.2.3", "--dist", "out"}, io.Discard)
	if err != nil {
		t.Fatal(err)
	}
	if opts.repository != "OWNER/sbx-connect" || opts.tag != "v1.2.3" || opts.dist != "out" {
		t.Fatalf("%+v", opts)
	}
	for _, args := range [][]string{
		{},
		{"--repository", "OWNER", "--tag", "v1.2.3"},
		{"--repository", "OWNER/repo", "--tag", "1.2.3"},
		{"--repository", "OWNER/repo", "--tag", "v1.2"},
		{"--repository", "OWNER/repo", "--tag", "v1.2.3", "extra"},
	} {
		if _, err := parseOptions(args, io.Discard); err == nil {
			t.Fatalf("accepted %q", args)
		}
	}
}

func TestGenerate(t *testing.T) {
	dist := t.TempDir()
	version := "1.2.3"
	var sums []string
	for _, osName := range []string{"darwin", "linux"} {
		for _, arch := range []string{"arm64", "amd64"} {
			name := "sbx-connect_" + version + "_" + osName + "_" + arch + ".tar.gz"
			data := []byte(name + "\n")
			if err := os.WriteFile(filepath.Join(dist, name), data, 0o600); err != nil {
				t.Fatal(err)
			}
			sum := sha256.Sum256(data)
			sums = append(sums, hex.EncodeToString(sum[:])+"  "+name)
		}
	}
	if err := os.WriteFile(filepath.Join(dist, "SHA256SUMS"), []byte(strings.Join(sums, "\n")+"\n"), 0o600); err != nil {
		t.Fatal(err)
	}

	formula, err := generate(options{repository: "OWNER/sbx-connect", tag: "v" + version, dist: dist})
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{
		"# Generated by go run ./scripts/homebrew-formula; do not edit.",
		`homepage "https://github.com/OWNER/sbx-connect"`,
		`version "1.2.3"`,
		"on_macos do",
		"on_linux do",
		"on_arm do",
		"on_intel do",
		`url "https://github.com/OWNER/sbx-connect/releases/download/v1.2.3/sbx-connect_1.2.3_darwin_arm64.tar.gz"`,
		`assert_match "sbx-connect #{version}", shell_output("#{bin}/sbx-connect version")`,
	} {
		if !strings.Contains(formula, want) {
			t.Fatalf("formula missing %q:\n%s", want, formula)
		}
	}
}

func TestGenerateRejectsChecksumMismatch(t *testing.T) {
	dist := t.TempDir()
	name := "sbx-connect_1.2.3_darwin_arm64.tar.gz"
	if err := os.WriteFile(filepath.Join(dist, name), []byte("archive"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dist, "SHA256SUMS"), []byte(strings.Repeat("0", 64)+"  "+name+"\n"), 0o600); err != nil {
		t.Fatal(err)
	}

	_, err := generate(options{repository: "OWNER/sbx-connect", tag: "v1.2.3", dist: dist})
	if err == nil || !strings.Contains(err.Error(), "checksum missing or mismatched") {
		t.Fatalf("error %v", err)
	}
}
