// Command homebrew-formula generates the sbx-connect Homebrew formula from
// GoReleaser release archives.
package main

import (
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

var (
	repositoryPattern = regexp.MustCompile(`^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$`)
	tagPattern        = regexp.MustCompile(`^v[0-9]+\.[0-9]+\.[0-9]+$`)
)

type options struct {
	repository string
	tag        string
	dist       string
}

func parseOptions(args []string, out io.Writer) (options, error) {
	var opts options
	flags := flag.NewFlagSet("homebrew-formula", flag.ContinueOnError)
	flags.SetOutput(out)
	flags.Usage = func() {
		_, _ = fmt.Fprintln(out, "Generate a Homebrew formula from exact GoReleaser release archives.\n\nUsage: homebrew-formula --repository OWNER/REPO --tag vMAJOR.MINOR.PATCH [--dist DIR]")
		flags.PrintDefaults()
	}
	flags.StringVar(&opts.repository, "repository", "", "GitHub OWNER/REPO")
	flags.StringVar(&opts.tag, "tag", "", "stable release tag, e.g. v0.1.0")
	flags.StringVar(&opts.dist, "dist", "dist", "GoReleaser dist directory")
	if err := flags.Parse(args); err != nil {
		return opts, err
	}
	if flags.NArg() != 0 {
		return opts, fmt.Errorf("unexpected positional arguments: %q", flags.Args())
	}
	if !repositoryPattern.MatchString(opts.repository) {
		return opts, fmt.Errorf("repository must be OWNER/REPO")
	}
	if !tagPattern.MatchString(opts.tag) {
		return opts, fmt.Errorf("tag must be a stable vMAJOR.MINOR.PATCH release")
	}
	return opts, nil
}

func readChecksums(path string) (map[string]string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	checksums := make(map[string]string)
	for lineNumber, line := range strings.Split(strings.TrimSpace(string(data)), "\n") {
		fields := strings.Fields(line)
		if len(fields) != 2 {
			return nil, fmt.Errorf("%s:%d: expected checksum and filename", path, lineNumber+1)
		}
		checksums[fields[1]] = fields[0]
	}
	return checksums, nil
}

func fileSHA256(path string) (string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	sum := sha256.Sum256(data)
	return hex.EncodeToString(sum[:]), nil
}

func generate(opts options) (string, error) {
	version := strings.TrimPrefix(opts.tag, "v")
	base := "https://github.com/" + opts.repository
	checksums, err := readChecksums(filepath.Join(opts.dist, "SHA256SUMS"))
	if err != nil {
		return "", fmt.Errorf("read checksums: %w", err)
	}

	var b strings.Builder
	fmt.Fprintln(&b, "# Generated by go run ./scripts/homebrew-formula; do not edit.")
	fmt.Fprintln(&b, "class SbxConnect < Formula")
	fmt.Fprintln(&b, `  desc "Connect ACP editors to coding agents in Docker Sandboxes"`)
	fmt.Fprintf(&b, "  homepage %q\n", base)
	fmt.Fprintf(&b, "  version %q\n", version)
	for _, target := range []struct {
		goos   string
		brewOS string
	}{
		{"darwin", "macos"},
		{"linux", "linux"},
	} {
		fmt.Fprintln(&b)
		fmt.Fprintf(&b, "  on_%s do\n", target.brewOS)
		for _, arch := range []struct {
			goarch   string
			brewArch string
		}{
			{"arm64", "arm"},
			{"amd64", "intel"},
		} {
			filename := fmt.Sprintf("sbx-connect_%s_%s_%s.tar.gz", version, target.goos, arch.goarch)
			digest, err := fileSHA256(filepath.Join(opts.dist, filename))
			if err != nil {
				return "", fmt.Errorf("checksum %s: %w", filename, err)
			}
			if checksums[filename] != digest {
				return "", fmt.Errorf("checksum missing or mismatched for %s", filename)
			}
			fmt.Fprintf(&b, "    on_%s do\n", arch.brewArch)
			fmt.Fprintf(&b, "      url %q\n", base+"/releases/download/"+opts.tag+"/"+filename)
			fmt.Fprintf(&b, "      sha256 %q\n", digest)
			fmt.Fprintln(&b, "    end")
		}
		fmt.Fprintln(&b, "  end")
	}
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "  def install")
	fmt.Fprintln(&b, `    bin.install "sbx-connect"`)
	fmt.Fprintln(&b, "  end")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "  def caveats")
	fmt.Fprintln(&b, "    <<~EOS")
	fmt.Fprintln(&b, "      Install Docker Sandboxes separately and authenticate with sbx login.")
	fmt.Fprintln(&b, "      To connect Zed, run: sbx-connect install zed")
	fmt.Fprintln(&b, "    EOS")
	fmt.Fprintln(&b, "  end")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "  test do")
	fmt.Fprintln(&b, `    assert_match "sbx-connect #{version}", shell_output("#{bin}/sbx-connect version")`)
	fmt.Fprintln(&b, "  end")
	fmt.Fprintln(&b, "end")
	return b.String(), nil
}

func main() {
	opts, err := parseOptions(os.Args[1:], os.Stderr)
	if errors.Is(err, flag.ErrHelp) {
		return
	}
	var formula string
	if err == nil {
		formula, err = generate(opts)
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "homebrew-formula:", err)
		os.Exit(1)
	}
	fmt.Print(formula)
}
